config/routes.rb
Rails.application.routes.draw do
  get 'painel' => 'admin_page#painel'

  root 'first_page#inicio'
  get 'entrar' => 'sessions#new'
  post 'entrar' => 'sessions#create'
  delete 'sair' => 'sessions#destroy'
  
  scope '/painel' do
    resources :estoques
    resources :cadastros do
      resources :orcamentos
      post '/painel/cadastros/:id/orcamentos/new' => 'orcamentos#create'
    end
  end
  

end

app/models/cadastro.rb
class Cadastro < ActiveRecord::Base
    has_many :orcamentos, dependent: :destroy
    
    # todas as validações nesta seção:
    before_save { email.downcase! }
    before_validation { cpf.delete! '.-' }
    before_validation { telefone_fixo.delete! '()-' }
    before_validation { telefone_celular.delete! '()-' }
    
    validates :nome, presence: true, length: { maximum: 50 } 
    validates :cpf, uniqueness: true, allow_blank: true, length: { is: 11 }
    validates :sexo, presence: true
    validates :rg, presence: true, uniqueness: true
    validates :profissao, length: { maximum: 50 }
    validates :endereco, presence: true, length: { maximum: 200 }
    validates :complemento, length: { maximum: 100 }
    validates :data_de_nascimento, presence: true
    validates :telefone_fixo, length: { maximum: 11 }
    validates :telefone_celular, uniqueness: true, length: { maximum: 11 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :cardiaco, length: { maximum: 140 }
    validates :pressao, presence: true
    validates :medicacao_em_uso, length: { maximum: 140 }
    validate :gestante_validate
    
    def gestante_validate
        errors.add(:gestante, "não pode ser do sexo masculino") if sexo == 'Masculino' && gestante
        errors.add(:previsao_parto, "precisa ser informado.") if (sexo == 'Feminino' && gestante && previsao_parto.nil?)
        errors.add(:gestante, "precisa ser selecionado se mês de gestação foi informado.") if (sexo == 'Feminino' && !gestante && !previsao_parto.nil?)
    end
    # fim de validações
    
    # sistema de busca para cadastro de clientes
    scoped_search :on => [:nome, :cpf, :rg] #campo de busca 
    
    def boolean_convert boolean
        boolean ? "Sim" : "Não"
    end
    
    def self.filtro atributos
        resultados = self.where nil
        atributos.each do |chave, valor|
            resultados = self.search_for(valor) if valor.present?
        end
        resultados
    end
    
    # define um callback de envio de email
    #after_create :envia_email_boasvindas 
    def envia_email_boasvindas
        ClienteMailer.boas_vindas(self).deliver
    end

end

app/controllers/cadastros_controller.rb
class CadastrosController < PrivateController
    before_filter :check_for_cancel, :only => [:create, :update]
    
    def index
      @cadastros = Cadastro.filtro(params.slice(:nome, :cpf, :rg)) #if params_no_empty?
    end
    
    def new
      @cadastro = Cadastro.new
    end
    
    def show
       @cadastro = Cadastro.find(params[:id])
    end
    
    def create
      @cadastro = Cadastro.new(cadastro_params)
      if @cadastro.save
        flash.now[:success] = "Ótimo! O novo cadastro está registrado."
        redirect_to @cadastro
      else
        render action: 'new'
      end 
    end
    
    def edit
      @cadastro = Cadastro.find(params[:id])
      @cadastro.data_de_nascimento = @cadastro.data_de_nascimento.strftime('%d/%m/%Y')
    end
    
    def update
      @cadastro = Cadastro.find(params[:id])
      if @cadastro.update_attributes(cadastro_params)
        flash.now[:success] = "As alterações foram salvas."
        redirect_to action: 'show', id: @cadastro
      else
        render 'edit'
      end
    end
    
    def destroy
      @cadastro = Cadastro.find params[:id]
      @cadastro.destroy
      redirect_to cadastros_path
      flash.now[:success] = "Excelente! O cadastro foi deletado."
    end
    
    def check_for_cancel
      redirect_to cadastros_path if params[:commit] == "Cancelar"
    end
    
    private
    
    def cadastro_params
      params.require(:cadastro).permit(:nome, :cpf, :sexo, :rg, :profissao, :endereco,
      :complemento, :data_de_nascimento, :telefone_fixo, :telefone_celular,
      :email, :cardiaco, :diabetes, :pressao, :gestante, :previsao_parto, :fumante, 
      :medicacao_em_uso)
    end
    
    def params_no_empty?
      params[:cpf].present? || params[:nome].present? || params[:rg].present?
    end
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/views/cadastros/_campos.html.erb
<div class="row">
  <div class="col-md-7 col-md-offset-2 col-sm-8 col-sm-offset-3">
    <div class="panel panel-default">
      <span><div class="panel-heading"><i class="glyphicon glyphicon-<%= glyphicon %>"></i><h1><%= yield(:title) %></h1></div></span>
      <hr>
      <h2>Dados Pessoais</h2>
      <div class="panel-body">
        <%= form_for(@cadastro) do |f| %>
          <%= render 'shared/error_messages', controller: @cadastro %>
        
          <div class="row">
            <div class="col-lg-6">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-user"></i></span>
                <%= f.text_field :nome, class: 'form-control', placeholder: 'Nome completo' %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-star"></i></span>
                <%= f.select :sexo, ['Masculino', 'Feminino'], {:prompt => 'Sexo'}, {class: 'form-control'} %>  
              </div>
            </div>
          </div>
          
          <div class="row">
            <div class="col-lg-6">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-credit-card"></i></span>
                <%= f.text_field :cpf, class: 'form-control', id: 'campoCPF', placeholder: 'CPF' %>
              </div>  
            </div>
            <div class="col-lg-6">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-credit-card"></i></span>
                <%= f.text_field :rg, class: 'form-control', id: 'campoRG', placeholder: 'RG' %>
              </div>
            </div>
          </div>
          
          <div class="row">
            <div class="col-lg-6">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                <%= f.text_field :data_de_nascimento, class: 'form-control', id: 'campoData', placeholder: 'Data de nascimento' %>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-wrench"></i></span>
                <%= f.text_field :profissao, class: 'form-control', placeholder: 'Profissão' %>
              </div>
            </div>
          </div>
          
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-home"></i></span>
            <%= f.text_field :endereco, class: 'form-control', placeholder: 'Endereço completo' %>
          </div>
          
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-home"></i></span>
            <%= f.text_field :complemento, class: 'form-control', placeholder: 'Complemento' %>
          </div>
          
          <div class="row">
            <div class="col-lg-6">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-earphone"></i></span>
                <%= f.telephone_field :telefone_fixo, class: 'form-control', id: 'campoTelefone', placeholder: 'Telefone fixo' %>
              </div>  
            </div>
            <div class="col-lg-6">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-phone"></i></span>
                <%= f.telephone_field number_to_phone(:telefone_celular, area_code: true), class: 'form-control', id: 'campoCelular', placeholder: 'Celular'%>
              </div>
            </div>
          </div>
          
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-envelope"></i></span>
            <%= f.email_field :email, class: 'form-control', placeholder: 'Endereço de email' %>
          </div>
          
          <hr>
          <h2>Anamnese</h2>
          
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-heart"></i></span>
            <%= f.select(:pressao, ['Normal', 'Hipertensão', 'Hipotensão'],{:prompt => 'Selecione o tipo de pressão sanguínea'}, {class: "form-control"}) %>
          </div>
          
          <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-list-alt"></i></span>
                <%= f.text_area :cardiaco, class: 'form-control', placeholder: 'Descreva todos os problemas cardíacos do cliente incluindo histórico de cardiopatias.' %>
              </div>  
            </div>
          </div>
          
          <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-list-alt"></i></span>
                <%= f.text_area :medicacao_em_uso, class: 'form-control', placeholder: 'Descreva as medicações que o cliente usa com frequência.'%>
              </div>
            </div>
          </div>
          
          <hr>
          
          <div class="row">
            <fieldset>
              <div class="center col-sm-12 col-md-6 com-lg-6">
                <div class="checkbox checkbox-default">
                  <%= f.check_box  :diabetes, html_options = { "class": "styled", "id": "checkbox1" } %>
                  <label for="checkbox1">É diabético?</label>
                </div>
              </div>
              <div class="center col-sm-12 col-md-6 col-lg-6">
                <div class="checkbox checkbox-default">
                  <%= f.check_box :fumante, html_options = { "class": "styled", "id": "checkbox2" } %>
                  <label for="checkbox2">É fumante?</label>
                </div>
              </div>
            </fieldset>
          </div>
          
          <hr>
          
          <div class="row">
            <fieldset>
              <div class="center col-sm-6 col-md-6 col-lg-6">
                <div class="checkbox checkbox-default">
                  <%= f.check_box :gestante, html_options = { "class": "styled", "id": "checkbox3" } %>
                  <label for="checkbox3">O paciente está gestante?</label>
                </div>
              </div>
              <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="input-group">
                  <span class="input-group-addon" id="basic-addon"><i class="glyphicon glyphicon-baby-formula"></i></span>
                   <%= f.select(:previsao_parto, (1..9), {:prompt => 'Caso afirmativo, selecione o mês de gestação'}, { type: 'integer', class:'form-control'} ) %>
                </div>
              </div>
            </fieldset>
          </div>
        </div> <!-- panel-body -->
        
        <div class="panel panel-footer">
          <div class="btn btn-group-justified">
            <div class="btn btn-group">
              <%= f.submit "Salvar", class: 'btn btn-success' %>
            </div>
            <div class="btn btn-group">
              <%= f.submit "Cancelar", class: 'btn btn-default' %>
            </div>
          </div>
        </div>
      <% end %>
    </div> <!-- panel-->
  </div> <!-- com-md-8 -->
</div> <!-- row -->

app/views/cadastros/_search.html.erb
<form action="<%= cadastros_path %>">
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon"><span class="glyphicon glyphicon-credit-card" aria-hidden= "true"></span></div>
      <%= text_field_tag :cpf, params[:cpf], class: 'form-control', id:'campoCPF', placeholder: "CPF (somente números)" %>
    </div>
    <div class="input-group">
      <div class="input-group-addon"><span class="glyphicon glyphicon-credit-card" aria-hidden= "true"></span></div>
      <%= text_field_tag :rg, params[:rg], class: 'form-control', id: 'campoRG', placeholder: "RG (somente números)" %>
    </div>
    <div class="input-group">
      <div class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden= "true"></span></div>
      <%= text_field_tag :nome, params[:nome], class: 'form-control', placeholder: "Nome do cliente" %>
    </div>
  </div>
  <%= submit_tag "Pesquisar", name: nil, class: "btn btn-success" %>
</form>

app/views/cadastros/_search_result.html.erb
<table class="table table-bordered table-hover">
    <thead>
        <th> Nome </th>
        <th> RG </th>
        <th> Telefone fixo </th>
        <th> Celular </th>
        <th> Data de registro </th>
    </thead>
    <tbody>
        <% @cadastros.each do |cadastro| %>
        <tr>
            <td> <%= link_to cadastro.nome, cadastro_path(cadastro) %> </td>
            <td> <%= cadastro.rg %> </td>
            <td> <%= cadastro.telefone_fixo %> </td>
            <td> <%= cadastro.telefone_celular %> </td>
            <td> <%= "#{cadastro.created_at.strftime("%d/%m/%Y")}" %> </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/cadastros/edit.html.erb
<% provide(:title, 'Atualizar Cadastro') %>

<%= render 'layouts/sidebar' %>

<%= render 'campos', glyphicon: 'edit' %>

app/views/cadastros/index.html.erb
<% provide(:title, 'Cadastros') %>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-5">
        <div class="panel panel-default">
            <span>
                <div class="panel-heading">
                    <i class="glyphicon glyphicon-search"></i>
                    <h1>Buscar um cadastro</h1>
                    <h4>Escolha um dos campos abaixo para pesquisar:</h4>
                </div>
            </span>
            <div class="panel-body"><%= render 'cadastros/search' %></div>
        </div>
    </div>
    <%  unless @cadastros.nil? %>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-7">
            <div class="panel panel-default">
              <div class="panel-heading">
                  <h3 class="panel-title">
                      <%= @cadastros.size if @cadastros.size > 0 %>
                      <%= 'resultado:' if @cadastros.size == 1 %>
                      <%= 'resultados:' if @cadastros.size > 1 %>
                      <%= 'Sem resultados' if @cadastros.size == 0 %>
                  </h3>
              </div>
              <%= render 'cadastros/search_result'%>
            </div>
        </div>
    <% end %>
</div>

app/views/cadastros/new.html.erb
<% provide(:title, 'Novo Cadastro') %>

<%= render 'cadastros/campos', glyphicon: 'plus' %>

app/views/cadastros/show.html.erb
<% provide(:title, @cadastro.nome) %>

<%= render 'layouts/sidebar' %>

<div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-3">
        <div class="panel panel-default">
            <span><div class="panel panel-heading"><i class="glyphicon glyphicon-list-alt"></i><h1>Dados do Cliente</h1></div></span>
            <div class="panel panel-body">
                <table class="table">
                    <tbody>
                        <tr>
                            <th scope="row">Nome</th>
                            <td><%= @cadastro.nome %></td>
                        </tr>
                        <tr>
                            <th scope="row">CPF</th>
                            <td><%= @cadastro.cpf %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Sexo</th>
                            <td><%= @cadastro.sexo %></td>
                        </tr>
                        <tr>
                            <th scope="raw">RG</th>
                            <td><%= @cadastro.rg %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Profissão</th>
                            <td><%= @cadastro.profissao %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Endereço</th>
                            <td><%= @cadastro.endereco %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Complemento</th>
                            <td><%= @cadastro.complemento %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Data de nascimento</th>
                            <td><%= @cadastro.data_de_nascimento.strftime('%d/%m/%Y') %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Telefone fixo</th>
                            <td><%= @cadastro.telefone_fixo %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Telefone celular</th>
                            <td><%= @cadastro.telefone_celular %></td>
                        </tr>
                        <tr>
                            <th scope="raw">E-mail</th>
                            <td><%= @cadastro.email %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Problemas cardíacos</th>
                            <td><%= @cadastro.cardiaco %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Diabetes</th>
                            <td><%= @cadastro.boolean_convert @cadastro.diabetes %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Pressão sanguinea</th>
                            <td><%= @cadastro.pressao %></td>
                        </tr>
                        <% if @cadastro.sexo == "Feminino"%>
                            <tr>
                                <th scope="raw">Gestante</th>
                                <td><%= @cadastro.boolean_convert @cadastro.gestante %></td>
                            </tr>
                            <% if @cadastro.gestante %>
                                <tr>
                                    <th scope="raw">Mês de gestação atual</th>
                                    <td><%= @cadastro.previsao_parto %></td>
                                </tr>
                            <% end %>
                        <% end %>
                        <tr>
                            <th scope="raw">Fumante</th>
                            <td><%= @cadastro.boolean_convert @cadastro.fumante %></td>
                        </tr>
                        <tr>
                            <th scope="raw">Medicação em uso</th>
                            <td><%= @cadastro.medicacao_em_uso %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div> <!-- panel -->
    </div> <!-- col -->
</div>