config/routes.rb
Rails.application.routes.draw do
  get 'painel' => 'admin_page#painel'

  root 'first_page#inicio'
  get 'entrar' => 'sessions#new'
  post 'entrar' => 'sessions#create'
  delete 'sair' => 'sessions#destroy'
  
  scope '/painel' do
    resources :estoques
    resources :cadastros do
      resources :orcamentos
      post '/painel/cadastros/:id/orcamentos/new' => 'orcamentos#create'
    end
  end
  

end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
    validates :nome, presence: true, length: {maximum: 30}
    validates :codigo_barras, presence: true, uniqueness: true, length: {maximum: 13}
    validates :descricao, length: {maximum: 50}
    validates :custo_unidade, presence: true
    
    scoped_search :on => [:nome, :codigo_barras]
    
    def self.filtro atributos
        resultados = self.where nil
        atributos.each do |chave, valor|
            resultados = self.search_for(valor) if valor.present?
        end
        resultados
    end
    
end

app/controllers/estoques_controller.rb
class EstoquesController < PrivateController
    
    def index
        @estoques = Estoque.filtro(params.slice(:codigo_barras, :nome)).paginate(page: params[:page], per_page: 10)
    end
    
    def new
        @estoque = Estoque.new
    end
    
    def create
        @estoque = Estoque.new(estoque_params)
        if @estoque.save
            flash.now[:success] = "O novo produto foi registrado."
            redirect_to estoques_path
        else
            render action: 'new'
        end 
    end
    
    def show
        @estoque = Estoque.find(params[:id])
    end
    
    def edit
        @estoque = Estoque.find(params[:id])
    end
    
    def update
        @estoque = Estoque.find(params[:id])
        if @estoque.update_attributes(estoque_params)
            flash.now[:success] = "As alterações foram salvas."
            redirect_to action: 'show', id: @estoque
        else
            render 'edit'
        end
    end
    
    def destroy
        @estoque = Estoque.find params[:id]
        redirect_to estoques_path if @estoque.destroy
        flash.now[:success] = "O produto foi excluído."
    end
    
    private
    
    def estoque_params
       params.require(:estoque).permit(:nome, :codigo_barras, :descricao, :quantidade, :validade, :custo_unidade) 
    end
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/views/estoques/_campos.html.erb
<div class="col-md-7 col-md-offset-2 col-sm-8 col-sm-offset-3">
    <div class="panel panel-default">
      <span><div class="panel-heading"><i class="glyphicon glyphicon-<%= glyphicon %>"dd></i><h1><%= yield(:title) %></h1></div></span>
        <div class="panel-body">
          <%= form_for @estoque do |f| %>
              <%= render 'shared/error_messages', controller: @estoque %>
              
            <div class="row">
                <div class="col-md-6">
                    <label for="nome">Nome</label>
                    <%= f.text_field :nome, class: 'form-control' %>
                </div>
                <div class="col-md-6">
                    <label for="codigo_barras">Código de barras</label>
                    <%= f.number_field :codigo_barras, min: 0, class: 'form-control' %>
                </div>
            </div><!-- div?class.row -->
            <div class="row">
                <div class="col-md-12">
                    <label for="descricao">Descrição</label>
                    <%= f.text_area :descricao, class: 'form-control' %>
                </div>
            </div><!-- div?class.row -->
            <div class="row">
                <div class="col-md-4">
                    <label for="validade">Validade</label>
                    <%= f.date_field :validade, class: 'form-control' %>
                </div>
                <div class="col-md-4">
                    <label for="custo_unidade">Custo unitário</label>
                    <%= f.number_field :custo_unidade, min: 0, step: 'any', class: 'form-control' %>
                </div>
                <div class="col-md-4">
                    <label for="quantidade">Quantidade</label>
                    <%= f.number_field :quantidade, min: 1, class: 'form-control' %>
                </div>
            </div><!-- div?class.row -->
            <div class="btn btn-justified">
                <%= f.submit "Salvar", class: 'btn btn-success' %>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/estoques/edit.html.erb
<% provide(:title, 'Atualizar Produto') %>

<%= render 'estoques/campos', glyphicon: 'edit' %>

app/views/estoques/index.html.erb
<% provide(:title, 'Ver estoque') %>
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-5">
    <div class="panel panel-default">
        <span>
            <div class="panel-heading">
                <i class="glyphicon glyphicon-search"></i>
                <h1>Buscar um produto</h1>
                <h4>Escolha um dos campos abaixo para pesquisar:</h4>
            </div>
        </span>
        <div class="panel-body"><%= render 'estoques/search' %></div>
    </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-6 col-lg-7">
    <div class="panel panel-default">
        <span>
            <div class="panel panel-heading">
                <i class="glyphicon glyphicon-list-alt"></i>
                <h1>Produtos registrados</h1>
            </div>
        </span>
        <div class="panel panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Código de barras</th>
                        <th>Unidades em estoque</th>
                    </tr>
                </thead>
                <tbody>
                    <% @estoques.each do |estoque| %>
                    <tr>
                        <td><%= estoque.nome %></td>
                        <td><%= estoque.codigo_barras %></td>
                        <td><%= estoque.quantidade %></td>
                        <td><%= link_to "Ver", estoque %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="painel painel-footer center">
            <%= will_paginate %>
        </div>
    </div> 
</div>

app/views/estoques/new.html.erb
<% provide(:title, 'Novo Produto') %>

<%= render 'estoques/campos', glyphicon: 'plus' %>

app/views/estoques/show.html.erb
<% provide(:title, 'Ver produto') %>

<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pull-right">
    <div class="panel panel-default">
        <span><div class="panel panel-heading"><i class="glyphicon glyphicon-list-alt"></i><h1><%= @estoque.nome %></h1></div></span>
        <div class="panel panel-body">
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">Código de barras</th>
                        <td><%= @estoque.codigo_barras %></td>
                    </tr>
                    <tr>
                        <th scope="raw">Descrição</th>
                        <td><%= @estoque.descricao %></td>
                    </tr>
                    <tr>
                        <th scope="raw">Quantidade</th>
                        <td><%= @estoque.quantidade %></td>
                    </tr>
                    <tr>
                        <th scope="raw">Validade</th>
                        <td><%= @estoque.validade %></td>
                    </tr>
                    <tr>
                        <th scope="raw">Custo unitário</th>
                        <td><%= @estoque.custo_unidade %></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="panel panel-footer">
            <div class="btn-group btn-group-justified" role="group" >
                <div class="btn">
                    <%= link_to "Editar", edit_estoque_path, class: 'btn btn-default' %>
                    <a href="#" class="btn btn-danger" data-target="#myModal" data-toggle="modal" %>
                        Excluir
                    </a>
                </div>
            </div>
        </div>
        
    </div> <!-- panel -->
</div> <!-- col -->

<%= render 'shared/modal_delete', controller: @estoque %>