config/routes.rb
Rails.application.routes.draw do
  get 'painel' => 'admin_page#painel'

  root 'first_page#inicio'
  get 'entrar' => 'sessions#new'
  post 'entrar' => 'sessions#create'
  delete 'sair' => 'sessions#destroy'
  
  scope '/painel' do
    resources :estoques
    resources :cadastros do
      resources :orcamentos
      post '/painel/cadastros/:id/orcamentos/new' => 'orcamentos#create'
    end
  end
  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <%= link_to "EloimOdonto", root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <% if logged_in? %>
      <div class="collapse navbar-collapse pull-right" id="bs-sidebar-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/painel">Painel <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Clientes <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a>
            <ul class="dropdown-menu forAnimate" role="menu">
              <li><%= link_to "Novo cadastro", new_cadastro_path %></li>
              <li><%= link_to "Buscar cadastro", cadastros_path %></li>
            </ul>
          </li>          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Finanças<span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-usd"></span></a>
            <ul class="dropdown-menu forAnimate" role="menu">
              <li><a href="#">Lançar crédito</a></li>
              <li><a href="#">Lançar débito</a></li>
              <li><a href="#">Ver balanço de contas</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Estoque<span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-inbox"></span></a>
            <ul class="dropdown-menu forAnimate" role="menu">
              <li><%= link_to "Visualizar", estoques_path %></li>
              <li><%= link_to "Novo produto", new_estoque_path %></li>
            </ul>
          </li>
          <li ><a href="#">Enviar e-mail <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-send"></span></a></li>
          <li class="divider"></li>
          <li><%= link_to "Sair", sair_path, method: :delete %></li>
        </ul>
      </div>
    <% else %>
      <%= link_to "Entrar", entrar_path, class: 'navbar-brand pull-right' %>
    <% end %>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="row">
    <nav class="navbar navbar-default sidebar" role="navigation" style="position: fixed">
        <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>      
            </div>
            <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="active"><%= link_to @cadastro do %> <%= @cadastro.nome %> <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span> <%end%> </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Ações <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-pencil"></span></a>
                  <ul class="dropdown-menu forAnimate" role="menu">
                    <li><%= link_to "Editar", edit_cadastro_path(@cadastro) %></li>
                    <li><a href="#" data-toggle="modal" data-target="#myModal">Excluir</a></li>
                    <li><a href="#">Imprimir</a></li>                    
                    <li class="divider"></li>
                    <li><a href="#">Enviar um e-mail</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Enviar um SMS</a></li>
                  </ul>
                </li>          
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Orçamentos <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-list-alt"></span></a>
                  <ul class="dropdown-menu forAnimate" role="menu">
                    <li><%= link_to cadastro_orcamentos_path(@cadastro) do %> Ver orçamentos<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-eye-open"></span><%end%></li>
                    <li class="divider"></li>
                    <li><%= link_to new_cadastro_orcamento_path(@cadastro) do %> Novo orçamento<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-edit"></span><%end%></li>
                  </ul>
                </li>        
                <li ><a href="#">Solicitações de serviços<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-tags"></span></a></li>
              </ul>
            </div>
        </div>
    </nav>
</div>

<%= render 'shared/modal_delete', controller: @cadastro %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
<head>
  <title><%= yield(:title) %> | EloimOdonto </title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> <!-- Bootstrap mobile first -->
  <%= favicon_link_tag 'favicon.png' %> <!-- favicon -->
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only"><%= message_type %>:</span>
            <%= message %>
          </div>
      <% end %>
      <%= yield %>
    </div>
  <%= debug(params) if Rails.env.development? %>
</body>

</html>